### PR TITLE
v2.32.0

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
If this doens't have much problem and can be merged, it should be merged to a new branch (v2.23.0) instead of the main branch.

**Comment by thewchan** [comment]
Requesting review and merge (to a different branch) @ocefpaf and others

**Comment by ocefpaf** [comment]
Can you elaborate on why you need an earlier patch release? In theory it should be only bugfixes from .0 to .3, no?

**Comment by thewchan** [comment]
There's a package pinning specifically to this version 🤷 https://github.com/lukasschwab/arxiv.py/blob/cd3ba8a42a4a2139da8ca26e997966c98a5b81f7/setup.py#L14 for https://github.com/conda-forge/arxiv-feedstock/pull/13

Also someone in the past also asked for this https://github.com/conda-forge/requests-feedstock/issues/62

**Comment by ocefpaf** [comment]
There is a big chance they are over-pinning. I'd patch that to use >=2.32.0,<2.33 instead and see how it goes.

**Comment by thewchan** [comment]
Got it, thanks!

**Pull request closed without merging**
