### PR TITLE
requests version 2.10.0

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Anyone want to review this?  I'm not a maintainer so cannot merge this myself.

**Comment by jakirkham** [comment]
Sorry, I'll merge it.

**Comment by jakirkham** [comment]
Thanks for bring it back up on the notification stack. 😄

**Comment by jjhelmus** [comment]
No problem and sorry to pester about this one.  It is on my list of "packages I want so I can make a conda-forge installer" which keeps getting shorter.

**Comment by jakirkham** [comment]
No worries. Waiting a week and repinging hardly counts as pestering. Agreed getting that installer up and going will really help solve a lot of problems.

**Pull request merged**
